AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: control-plane-playground
Resources:
  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "cpln-merck-dev-01"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - arn:aws:iam::957753459089:user/controlplane-driver
            - arn:aws:iam::957753459089:role/controlplane-driver
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId: merck-dev-01
      Policies:
      - PolicyName: passrole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: CreateRoles
            Effect: Allow
            Action:
            - iam:CreatePolicy
            - iam:UpdateAssumeRolePolicy
            - iam:DetachRolePolicy
            - iam:TagRole
            - iam:UpdateRoleDescription
            - iam:DeletePolicy
            - iam:CreateRole
            - iam:DeleteRole
            - iam:AttachRolePolicy
            - iam:UpdateRole
            - iam:PutRolePolicy
            - iam:TagPolicy
            Resource: "*"